name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x' # Adjust to your .NET version
    
    - name: Restore
      run: dotnet restore
      
    - name: Build and Publish
      run: |
        dotnet publish Rice.Showcase -c Release -o out

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out/wwwroot  # Adjust if your output directory is different
